// Generated by gencpp from file sdk/BoudingBox.msg
// DO NOT EDIT!


#ifndef SDK_MESSAGE_BOUDINGBOX_H
#define SDK_MESSAGE_BOUDINGBOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdk
{
template <class ContainerAllocator>
struct BoudingBox_
{
  typedef BoudingBox_<ContainerAllocator> Type;

  BoudingBox_()
    : clss(0)
    , x(0)
    , y(0)
    , width(0)
    , height(0)  {
    }
  BoudingBox_(const ContainerAllocator& _alloc)
    : clss(0)
    , x(0)
    , y(0)
    , width(0)
    , height(0)  {
  (void)_alloc;
    }



   typedef int32_t _clss_type;
  _clss_type clss;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef int32_t _width_type;
  _width_type width;

   typedef int32_t _height_type;
  _height_type height;





  typedef boost::shared_ptr< ::sdk::BoudingBox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdk::BoudingBox_<ContainerAllocator> const> ConstPtr;

}; // struct BoudingBox_

typedef ::sdk::BoudingBox_<std::allocator<void> > BoudingBox;

typedef boost::shared_ptr< ::sdk::BoudingBox > BoudingBoxPtr;
typedef boost::shared_ptr< ::sdk::BoudingBox const> BoudingBoxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdk::BoudingBox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdk::BoudingBox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdk::BoudingBox_<ContainerAllocator1> & lhs, const ::sdk::BoudingBox_<ContainerAllocator2> & rhs)
{
  return lhs.clss == rhs.clss &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.width == rhs.width &&
    lhs.height == rhs.height;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdk::BoudingBox_<ContainerAllocator1> & lhs, const ::sdk::BoudingBox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdk::BoudingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdk::BoudingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk::BoudingBox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk::BoudingBox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk::BoudingBox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk::BoudingBox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdk::BoudingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e97d25d86d41daea836bf7b8768d1b5e";
  }

  static const char* value(const ::sdk::BoudingBox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe97d25d86d41daeaULL;
  static const uint64_t static_value2 = 0x836bf7b8768d1b5eULL;
};

template<class ContainerAllocator>
struct DataType< ::sdk::BoudingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdk/BoudingBox";
  }

  static const char* value(const ::sdk::BoudingBox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdk::BoudingBox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 clss\n"
"int32 x\n"
"int32 y\n"
"int32 width\n"
"int32 height\n"
;
  }

  static const char* value(const ::sdk::BoudingBox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdk::BoudingBox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.clss);
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BoudingBox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdk::BoudingBox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdk::BoudingBox_<ContainerAllocator>& v)
  {
    s << indent << "clss: ";
    Printer<int32_t>::stream(s, indent + "  ", v.clss);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "width: ";
    Printer<int32_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDK_MESSAGE_BOUDINGBOX_H
