// Generated by gencpp from file sdk/EndPos.msg
// DO NOT EDIT!


#ifndef SDK_MESSAGE_ENDPOS_H
#define SDK_MESSAGE_ENDPOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdk
{
template <class ContainerAllocator>
struct EndPos_
{
  typedef EndPos_<ContainerAllocator> Type;

  EndPos_()
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , zz(0.0)  {
    }
  EndPos_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)
    , zz(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;

   typedef float _zz_type;
  _zz_type zz;





  typedef boost::shared_ptr< ::sdk::EndPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdk::EndPos_<ContainerAllocator> const> ConstPtr;

}; // struct EndPos_

typedef ::sdk::EndPos_<std::allocator<void> > EndPos;

typedef boost::shared_ptr< ::sdk::EndPos > EndPosPtr;
typedef boost::shared_ptr< ::sdk::EndPos const> EndPosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdk::EndPos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdk::EndPos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdk::EndPos_<ContainerAllocator1> & lhs, const ::sdk::EndPos_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z &&
    lhs.zz == rhs.zz;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdk::EndPos_<ContainerAllocator1> & lhs, const ::sdk::EndPos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdk::EndPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdk::EndPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk::EndPos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk::EndPos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk::EndPos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk::EndPos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdk::EndPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2394776e9e3be65fdd9b82cae0a0fe58";
  }

  static const char* value(const ::sdk::EndPos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2394776e9e3be65fULL;
  static const uint64_t static_value2 = 0xdd9b82cae0a0fe58ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdk::EndPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdk/EndPos";
  }

  static const char* value(const ::sdk::EndPos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdk::EndPos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 zz\n"
;
  }

  static const char* value(const ::sdk::EndPos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdk::EndPos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.zz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EndPos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdk::EndPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdk::EndPos_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "zz: ";
    Printer<float>::stream(s, indent + "  ", v.zz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDK_MESSAGE_ENDPOS_H
