// Generated by gencpp from file sdk/GetEnvironmentRequest.msg
// DO NOT EDIT!


#ifndef SDK_MESSAGE_GETENVIRONMENTREQUEST_H
#define SDK_MESSAGE_GETENVIRONMENTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdk
{
template <class ContainerAllocator>
struct GetEnvironmentRequest_
{
  typedef GetEnvironmentRequest_<ContainerAllocator> Type;

  GetEnvironmentRequest_()
    : search(false)  {
    }
  GetEnvironmentRequest_(const ContainerAllocator& _alloc)
    : search(false)  {
  (void)_alloc;
    }



   typedef uint8_t _search_type;
  _search_type search;





  typedef boost::shared_ptr< ::sdk::GetEnvironmentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdk::GetEnvironmentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetEnvironmentRequest_

typedef ::sdk::GetEnvironmentRequest_<std::allocator<void> > GetEnvironmentRequest;

typedef boost::shared_ptr< ::sdk::GetEnvironmentRequest > GetEnvironmentRequestPtr;
typedef boost::shared_ptr< ::sdk::GetEnvironmentRequest const> GetEnvironmentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdk::GetEnvironmentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdk::GetEnvironmentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdk::GetEnvironmentRequest_<ContainerAllocator1> & lhs, const ::sdk::GetEnvironmentRequest_<ContainerAllocator2> & rhs)
{
  return lhs.search == rhs.search;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdk::GetEnvironmentRequest_<ContainerAllocator1> & lhs, const ::sdk::GetEnvironmentRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdk::GetEnvironmentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdk::GetEnvironmentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk::GetEnvironmentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk::GetEnvironmentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk::GetEnvironmentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk::GetEnvironmentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdk::GetEnvironmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1ab0c1a6e3a68486019eedaa514c28";
  }

  static const char* value(const ::sdk::GetEnvironmentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1ab0c1a6e3a684ULL;
  static const uint64_t static_value2 = 0x86019eedaa514c28ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdk::GetEnvironmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdk/GetEnvironmentRequest";
  }

  static const char* value(const ::sdk::GetEnvironmentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdk::GetEnvironmentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool search\n"
;
  }

  static const char* value(const ::sdk::GetEnvironmentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdk::GetEnvironmentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.search);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetEnvironmentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdk::GetEnvironmentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdk::GetEnvironmentRequest_<ContainerAllocator>& v)
  {
    s << indent << "search: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.search);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDK_MESSAGE_GETENVIRONMENTREQUEST_H
