// Generated by gencpp from file sdk/GetEnvironment.msg
// DO NOT EDIT!


#ifndef SDK_MESSAGE_GETENVIRONMENT_H
#define SDK_MESSAGE_GETENVIRONMENT_H

#include <ros/service_traits.h>


#include <sdk/GetEnvironmentRequest.h>
#include <sdk/GetEnvironmentResponse.h>


namespace sdk
{

struct GetEnvironment
{

typedef GetEnvironmentRequest Request;
typedef GetEnvironmentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetEnvironment
} // namespace sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sdk::GetEnvironment > {
  static const char* value()
  {
    return "6e30450642d80126377a1be66fd69859";
  }

  static const char* value(const ::sdk::GetEnvironment&) { return value(); }
};

template<>
struct DataType< ::sdk::GetEnvironment > {
  static const char* value()
  {
    return "sdk/GetEnvironment";
  }

  static const char* value(const ::sdk::GetEnvironment&) { return value(); }
};


// service_traits::MD5Sum< ::sdk::GetEnvironmentRequest> should match
// service_traits::MD5Sum< ::sdk::GetEnvironment >
template<>
struct MD5Sum< ::sdk::GetEnvironmentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sdk::GetEnvironment >::value();
  }
  static const char* value(const ::sdk::GetEnvironmentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdk::GetEnvironmentRequest> should match
// service_traits::DataType< ::sdk::GetEnvironment >
template<>
struct DataType< ::sdk::GetEnvironmentRequest>
{
  static const char* value()
  {
    return DataType< ::sdk::GetEnvironment >::value();
  }
  static const char* value(const ::sdk::GetEnvironmentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sdk::GetEnvironmentResponse> should match
// service_traits::MD5Sum< ::sdk::GetEnvironment >
template<>
struct MD5Sum< ::sdk::GetEnvironmentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sdk::GetEnvironment >::value();
  }
  static const char* value(const ::sdk::GetEnvironmentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdk::GetEnvironmentResponse> should match
// service_traits::DataType< ::sdk::GetEnvironment >
template<>
struct DataType< ::sdk::GetEnvironmentResponse>
{
  static const char* value()
  {
    return DataType< ::sdk::GetEnvironment >::value();
  }
  static const char* value(const ::sdk::GetEnvironmentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SDK_MESSAGE_GETENVIRONMENT_H
