// Generated by gencpp from file sdk/ManageNodeResponse.msg
// DO NOT EDIT!


#ifndef SDK_MESSAGE_MANAGENODERESPONSE_H
#define SDK_MESSAGE_MANAGENODERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdk
{
template <class ContainerAllocator>
struct ManageNodeResponse_
{
  typedef ManageNodeResponse_<ContainerAllocator> Type;

  ManageNodeResponse_()
    : success(false)
    , message()  {
    }
  ManageNodeResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::sdk::ManageNodeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdk::ManageNodeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ManageNodeResponse_

typedef ::sdk::ManageNodeResponse_<std::allocator<void> > ManageNodeResponse;

typedef boost::shared_ptr< ::sdk::ManageNodeResponse > ManageNodeResponsePtr;
typedef boost::shared_ptr< ::sdk::ManageNodeResponse const> ManageNodeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdk::ManageNodeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdk::ManageNodeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdk::ManageNodeResponse_<ContainerAllocator1> & lhs, const ::sdk::ManageNodeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdk::ManageNodeResponse_<ContainerAllocator1> & lhs, const ::sdk::ManageNodeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdk::ManageNodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdk::ManageNodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk::ManageNodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk::ManageNodeResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk::ManageNodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk::ManageNodeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdk::ManageNodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::sdk::ManageNodeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::sdk::ManageNodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdk/ManageNodeResponse";
  }

  static const char* value(const ::sdk::ManageNodeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdk::ManageNodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success  # Operation success or failure\n"
"string message  # Success or failure message\n"
"\n"
;
  }

  static const char* value(const ::sdk::ManageNodeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdk::ManageNodeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ManageNodeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdk::ManageNodeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdk::ManageNodeResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDK_MESSAGE_MANAGENODERESPONSE_H
