// Generated by gencpp from file sdk/ManageNode.msg
// DO NOT EDIT!


#ifndef SDK_MESSAGE_MANAGENODE_H
#define SDK_MESSAGE_MANAGENODE_H

#include <ros/service_traits.h>


#include <sdk/ManageNodeRequest.h>
#include <sdk/ManageNodeResponse.h>


namespace sdk
{

struct ManageNode
{

typedef ManageNodeRequest Request;
typedef ManageNodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ManageNode
} // namespace sdk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sdk::ManageNode > {
  static const char* value()
  {
    return "4e70dc4b2243d8981cdd9ef1969809ac";
  }

  static const char* value(const ::sdk::ManageNode&) { return value(); }
};

template<>
struct DataType< ::sdk::ManageNode > {
  static const char* value()
  {
    return "sdk/ManageNode";
  }

  static const char* value(const ::sdk::ManageNode&) { return value(); }
};


// service_traits::MD5Sum< ::sdk::ManageNodeRequest> should match
// service_traits::MD5Sum< ::sdk::ManageNode >
template<>
struct MD5Sum< ::sdk::ManageNodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sdk::ManageNode >::value();
  }
  static const char* value(const ::sdk::ManageNodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdk::ManageNodeRequest> should match
// service_traits::DataType< ::sdk::ManageNode >
template<>
struct DataType< ::sdk::ManageNodeRequest>
{
  static const char* value()
  {
    return DataType< ::sdk::ManageNode >::value();
  }
  static const char* value(const ::sdk::ManageNodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sdk::ManageNodeResponse> should match
// service_traits::MD5Sum< ::sdk::ManageNode >
template<>
struct MD5Sum< ::sdk::ManageNodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sdk::ManageNode >::value();
  }
  static const char* value(const ::sdk::ManageNodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sdk::ManageNodeResponse> should match
// service_traits::DataType< ::sdk::ManageNode >
template<>
struct DataType< ::sdk::ManageNodeResponse>
{
  static const char* value()
  {
    return DataType< ::sdk::ManageNode >::value();
  }
  static const char* value(const ::sdk::ManageNodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SDK_MESSAGE_MANAGENODE_H
