// Generated by gencpp from file sdk/WaistControl.msg
// DO NOT EDIT!


#ifndef SDK_MESSAGE_WAISTCONTROL_H
#define SDK_MESSAGE_WAISTCONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sdk
{
template <class ContainerAllocator>
struct WaistControl_
{
  typedef WaistControl_<ContainerAllocator> Type;

  WaistControl_()
    : waist_q()  {
      waist_q.assign(0.0);
  }
  WaistControl_(const ContainerAllocator& _alloc)
    : waist_q()  {
  (void)_alloc;
      waist_q.assign(0.0);
  }



   typedef boost::array<float, 3>  _waist_q_type;
  _waist_q_type waist_q;





  typedef boost::shared_ptr< ::sdk::WaistControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sdk::WaistControl_<ContainerAllocator> const> ConstPtr;

}; // struct WaistControl_

typedef ::sdk::WaistControl_<std::allocator<void> > WaistControl;

typedef boost::shared_ptr< ::sdk::WaistControl > WaistControlPtr;
typedef boost::shared_ptr< ::sdk::WaistControl const> WaistControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sdk::WaistControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sdk::WaistControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sdk::WaistControl_<ContainerAllocator1> & lhs, const ::sdk::WaistControl_<ContainerAllocator2> & rhs)
{
  return lhs.waist_q == rhs.waist_q;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sdk::WaistControl_<ContainerAllocator1> & lhs, const ::sdk::WaistControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sdk

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::sdk::WaistControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sdk::WaistControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk::WaistControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sdk::WaistControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk::WaistControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sdk::WaistControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sdk::WaistControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20a59e522905a9c10dfde9315ec5820d";
  }

  static const char* value(const ::sdk::WaistControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20a59e522905a9c1ULL;
  static const uint64_t static_value2 = 0x0dfde9315ec5820dULL;
};

template<class ContainerAllocator>
struct DataType< ::sdk::WaistControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sdk/WaistControl";
  }

  static const char* value(const ::sdk::WaistControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sdk::WaistControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[3] waist_q\n"
;
  }

  static const char* value(const ::sdk::WaistControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sdk::WaistControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waist_q);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct WaistControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sdk::WaistControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sdk::WaistControl_<ContainerAllocator>& v)
  {
    s << indent << "waist_q[]" << std::endl;
    for (size_t i = 0; i < v.waist_q.size(); ++i)
    {
      s << indent << "  waist_q[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.waist_q[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SDK_MESSAGE_WAISTCONTROL_H
